# Generated by Django 3.2 on 2023-06-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_alter_curso_camada'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_alta',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_alta',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
