# Generated by Django 3.2 on 2023-06-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_auto_20230608_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='emial',
            new_name='email',
        ),
    ]
