# Generated by Django 3.2 on 2023-06-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_rename_emial_profesor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='emial',
            new_name='email',
        ),
    ]
