# Generated by Django 3.2 on 2023-06-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_rename_emial_estudiante_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='fecha_de_Entrega',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
