# Generated by Django 3.2 on 2023-06-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_remove_entregable_fecha_de_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='fecha_de_Entrega',
            field=models.DateTimeField(null=True),
        ),
    ]
